name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature and why it would be useful
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example usage
      placeholder: |
        ```bash
        dtctl your-command --example
        ```
